name: riverpod_example
description: Source code for the `flutter_riverpod` tutorial
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.1
  dio: ^5.0.2
  riverpod_annotation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
